<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWT1hkmq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWT1hkmq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWT1hkmq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWT1hkmq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWT1hkmq\App_KernelDevDebugContainer([
    'container.build_hash' => 'WT1hkmq',
    'container.build_id' => 'bd663587',
    'container.build_time' => 1717070487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWT1hkmq');
