<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZK4e35q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZK4e35q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZK4e35q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZK4e35q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZK4e35q\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZK4e35q',
    'container.build_id' => '392b1c8f',
    'container.build_time' => 1716245435,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZK4e35q');
