<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RWsgqL7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rWsgqL7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rWsgqL7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cursadaDocente' => ['privates', '.errored..service_locator.rWsgqL7.App\\Entity\\CursadaDocente', NULL, 'Cannot autowire service ".service_locator.rWsgqL7": it references class "App\\Entity\\CursadaDocente" but no such service exists.'],
        ], [
            'cursadaDocente' => 'App\\Entity\\CursadaDocente',
        ]);
    }
}
