<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L8U5ARService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l8U5AR_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l8U5AR_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paisRepository' => ['privates', 'App\\Repository\\PaisRepository', 'getPaisRepositoryService', true],
        ], [
            'paisRepository' => 'App\\Repository\\PaisRepository',
        ]);
    }
}
