<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AHzFaQIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aHzFaQI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aHzFaQI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'localidadRepository' => ['privates', 'App\\Repository\\LocalidadRepository', 'getLocalidadRepositoryService', true],
        ], [
            'localidadRepository' => 'App\\Repository\\LocalidadRepository',
        ]);
    }
}
