<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I2o8IfAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I2o8IfA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I2o8IfA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comision' => ['privates', '.errored..service_locator.I2o8IfA.App\\Entity\\Comision', NULL, 'Cannot autowire service ".service_locator.I2o8IfA": it references class "App\\Entity\\Comision" but no such service exists.'],
        ], [
            'comision' => 'App\\Entity\\Comision',
        ]);
    }
}
