<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X8Caz58Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X8Caz58' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X8Caz58'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'correlativaRepository' => ['privates', 'App\\Repository\\CorrelativaRepository', 'getCorrelativaRepositoryService', true],
        ], [
            'correlativaRepository' => 'App\\Repository\\CorrelativaRepository',
        ]);
    }
}
