<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_14NWBxHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.14NWBxH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.14NWBxH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tecnicaturaRepository' => ['privates', 'App\\Repository\\TecnicaturaRepository', 'getTecnicaturaRepositoryService', true],
        ], [
            'tecnicaturaRepository' => 'App\\Repository\\TecnicaturaRepository',
        ]);
    }
}
