<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__0vGhcyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..0vGhcy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..0vGhcy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tecnicatura' => ['privates', '.errored..service_locator..0vGhcy.App\\Entity\\Tecnicatura', NULL, 'Cannot autowire service ".service_locator..0vGhcy": it references class "App\\Entity\\Tecnicatura" but no such service exists.'],
            'tecnicaturaRepository' => ['privates', 'App\\Repository\\TecnicaturaRepository', 'getTecnicaturaRepositoryService', true],
        ], [
            'tecnicatura' => 'App\\Entity\\Tecnicatura',
            'tecnicaturaRepository' => 'App\\Repository\\TecnicaturaRepository',
        ]);
    }
}
