<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocente2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sRmH63H.App\Entity\Docente' shared service.
     *
     * @return \App\Entity\Docente
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.sRmH63H": it references class "App\\Entity\\Docente" but no such service exists.');
    }
}
