<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabilitante2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zHcbPEg.App\Entity\Habilitante' shared service.
     *
     * @return \App\Entity\Habilitante
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zHcbPEg": it references class "App\\Entity\\Habilitante" but no such service exists.');
    }
}
