<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModalidad2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.k.xcjCc.App\Entity\Modalidad' shared service.
     *
     * @return \App\Entity\Modalidad
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.k.xcjCc": it references class "App\\Entity\\Modalidad" but no such service exists.');
    }
}
