<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersona2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UuLSni7.App\Entity\Persona' shared service.
     *
     * @return \App\Entity\Persona
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.UuLSni7": it references class "App\\Entity\\Persona" but no such service exists.');
    }
}
