<?php

namespace ContainerWT1hkmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProvincia2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DqTasRE.App\Entity\Provincia' shared service.
     *
     * @return \App\Entity\Provincia
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.DqTasRE": it references class "App\\Entity\\Provincia" but no such service exists.');
    }
}
