<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VWX6yVvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VWX6yVv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VWX6yVv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cursada' => ['privates', '.errored..service_locator.VWX6yVv.App\\Entity\\Cursada', NULL, 'Cannot autowire service ".service_locator.VWX6yVv": it references class "App\\Entity\\Cursada" but no such service exists.'],
        ], [
            'cursada' => 'App\\Entity\\Cursada',
        ]);
    }
}
