<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yej9iZfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yej9iZf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yej9iZf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comisionRepository' => ['privates', 'App\\Repository\\ComisionRepository', 'getComisionRepositoryService', true],
        ], [
            'comisionRepository' => 'App\\Repository\\ComisionRepository',
        ]);
    }
}
