<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yv4GhdlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yv4Ghdl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yv4Ghdl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'habilitante' => ['privates', '.errored..service_locator.Yv4Ghdl.App\\Entity\\Habilitante', NULL, 'Cannot autowire service ".service_locator.Yv4Ghdl": it references class "App\\Entity\\Habilitante" but no such service exists.'],
        ], [
            'habilitante' => 'App\\Entity\\Habilitante',
        ]);
    }
}
