<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hxsiru_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hxsiru.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Hxsiru.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asignaturaRepository' => ['privates', 'App\\Repository\\AsignaturaRepository', 'getAsignaturaRepositoryService', true],
        ], [
            'asignaturaRepository' => 'App\\Repository\\AsignaturaRepository',
        ]);
    }
}
