<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oe2LQNYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Oe2LQNY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Oe2LQNY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'telefonoRepository' => ['privates', 'App\\Repository\\TelefonoRepository', 'getTelefonoRepositoryService', true],
        ], [
            'telefonoRepository' => 'App\\Repository\\TelefonoRepository',
        ]);
    }
}
