<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R9mCt2iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R9mCt2i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R9mCt2i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'institucion' => ['privates', '.errored..service_locator.R9mCt2i.App\\Entity\\Institucion', NULL, 'Cannot autowire service ".service_locator.R9mCt2i": it references class "App\\Entity\\Institucion" but no such service exists.'],
        ], [
            'institucion' => 'App\\Entity\\Institucion',
        ]);
    }
}
