<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B2M12_QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b2M12.q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b2M12.q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'instituto' => ['privates', '.errored..service_locator.b2M12.q.App\\Entity\\Instituto', NULL, 'Cannot autowire service ".service_locator.b2M12.q": it references class "App\\Entity\\Instituto" but no such service exists.'],
        ], [
            'instituto' => 'App\\Entity\\Instituto',
        ]);
    }
}
