<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAsignaturaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WrECdGN.App\Entity\Asignatura' shared service.
     *
     * @return \App\Entity\Asignatura
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WrECdGN": it references class "App\\Entity\\Asignatura" but no such service exists.');
    }
}
