<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCursadaDocente2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rWsgqL7.App\Entity\CursadaDocente' shared service.
     *
     * @return \App\Entity\CursadaDocente
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.rWsgqL7": it references class "App\\Entity\\CursadaDocente" but no such service exists.');
    }
}
