<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitucionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.R9mCt2i.App\Entity\Institucion' shared service.
     *
     * @return \App\Entity\Institucion
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.R9mCt2i": it references class "App\\Entity\\Institucion" but no such service exists.');
    }
}
