<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalidad2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SxwhuBD.App\Entity\Localidad' shared service.
     *
     * @return \App\Entity\Localidad
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SxwhuBD": it references class "App\\Entity\\Localidad" but no such service exists.');
    }
}
