<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_AccessMapService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.access_map' shared service.
     *
     * @return \Symfony\Component\Security\Http\AccessMap
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'AccessMapInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'AccessMap.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-foundation'.\DIRECTORY_SEPARATOR.'RequestMatcherInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-foundation'.\DIRECTORY_SEPARATOR.'RequestMatcher.php';

        $container->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/alumno'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/asignatura'), [0 => 'ROLE_SUPER_ADMIN', 1 => 'ROLE_ALUMNO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/comision'), [0 => 'ROLE_SUPER_ADMIN', 1 => 'ROLE_ALUMNO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/correlativa'), [0 => 'ROLE_SUPER_ADMIN', 1 => 'ROLE_ALUMNO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/cursada'), [0 => 'ROLE_SUPER_ADMIN', 1 => 'ROLE_ALUMNO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/cursadadocente'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/docente'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/examen/alumno'), [0 => 'ROLE_SUPER_ADMIN', 1 => 'ROLE_ALUMNO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/examen/final'), [0 => 'ROLE_SUPER_ADMIN', 1 => 'ROLE_ALUMNO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/habilitante'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/home'), [0 => 'ROLE_SUPER_ADMIN', 1 => 'ROLE_ADMIN', 2 => 'ROLE_DOCENTE', 3 => 'ROLE_ALUMNO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/instituto'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/localidad'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/modalidad'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/pais'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/perona'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/provincia'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/region'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/revista'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/security'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/tecnicatura'), [0 => 'ROLE_SUPER_ADMIN', 1 => 'ROLE_ALUMNO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/telefono'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/titulo'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/turno'), [0 => 'ROLE_SUPER_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/user'), [0 => 'ROLE_SUPER_ADMIN'], NULL);

        return $instance;
    }
}
