<?php

namespace ContainerZK4e35q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTecnicatura2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uCUCD3W.App\Entity\Tecnicatura' shared service.
     *
     * @return \App\Entity\Tecnicatura
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.uCUCD3W": it references class "App\\Entity\\Tecnicatura" but no such service exists.');
    }
}
