<?php

namespace ContainerPEfUA6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HFQFqGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hFQFq_g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hFQFq_g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alumno' => ['privates', '.errored..service_locator.hFQFq_g.App\\Entity\\Alumno', NULL, 'Cannot autowire service ".service_locator.hFQFq_g": it references class "App\\Entity\\Alumno" but no such service exists.'],
        ], [
            'alumno' => 'App\\Entity\\Alumno',
        ]);
    }
}
