<?php

namespace ContainerPEfUA6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RhEh58EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rhEh58E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rhEh58E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asignatura' => ['privates', '.errored..service_locator.rhEh58E.App\\Entity\\Asignatura', NULL, 'Cannot autowire service ".service_locator.rhEh58E": it references class "App\\Entity\\Asignatura" but no such service exists.'],
        ], [
            'asignatura' => 'App\\Entity\\Asignatura',
        ]);
    }
}
