<?php

namespace ContainerPEfUA6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GlfVhgCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GlfVhgC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GlfVhgC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'turno' => ['privates', '.errored..service_locator.GlfVhgC.App\\Entity\\Turno', NULL, 'Cannot autowire service ".service_locator.GlfVhgC": it references class "App\\Entity\\Turno" but no such service exists.'],
            'turnoRepository' => ['privates', 'App\\Repository\\TurnoRepository', 'getTurnoRepositoryService', true],
        ], [
            'turno' => 'App\\Entity\\Turno',
            'turnoRepository' => 'App\\Repository\\TurnoRepository',
        ]);
    }
}
