<?php

namespace ContainerPEfUA6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UCUCD3WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uCUCD3W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uCUCD3W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tecnicatura' => ['privates', '.errored..service_locator.uCUCD3W.App\\Entity\\Tecnicatura', NULL, 'Cannot autowire service ".service_locator.uCUCD3W": it references class "App\\Entity\\Tecnicatura" but no such service exists.'],
        ], [
            'tecnicatura' => 'App\\Entity\\Tecnicatura',
        ]);
    }
}
