<?php

namespace ContainerPEfUA6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AICXjxeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AICXjxe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AICXjxe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'docente' => ['privates', '.errored..service_locator.AICXjxe.App\\Entity\\Docente', NULL, 'Cannot autowire service ".service_locator.AICXjxe": it references class "App\\Entity\\Docente" but no such service exists.'],
            'docenteRepository' => ['privates', 'App\\Repository\\DocenteRepository', 'getDocenteRepositoryService', true],
        ], [
            'docente' => 'App\\Entity\\Docente',
            'docenteRepository' => 'App\\Repository\\DocenteRepository',
        ]);
    }
}
