<?php

namespace ContainerPEfUA6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6akdvidService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6akdvid' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6akdvid'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pai' => ['privates', '.errored..service_locator.6akdvid.App\\Entity\\Pais', NULL, 'Cannot autowire service ".service_locator.6akdvid": it references class "App\\Entity\\Pais" but no such service exists.'],
            'paisRepository' => ['privates', 'App\\Repository\\PaisRepository', 'getPaisRepositoryService', true],
        ], [
            'pai' => 'App\\Entity\\Pais',
            'paisRepository' => 'App\\Repository\\PaisRepository',
        ]);
    }
}
