<?php

namespace ContainerPEfUA6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCorrelativaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.R4Vsjqn.App\Entity\Correlativa' shared service.
     *
     * @return \App\Entity\Correlativa
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.R4Vsjqn": it references class "App\\Entity\\Correlativa" but no such service exists.');
    }
}
