<?php

namespace ContainerPEfUA6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.S6cVw0t.App\Entity\Persona' shared service.
     *
     * @return \App\Entity\Persona
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.S6cVw0t": it references class "App\\Entity\\Persona" but no such service exists.');
    }
}
