<?php

namespace ContainerPEfUA6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevista2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uDOEynA.App\Entity\Revista' shared service.
     *
     * @return \App\Entity\Revista
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.uDOEynA": it references class "App\\Entity\\Revista" but no such service exists.');
    }
}
