<?php

namespace ContainerPEfUA6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelefono2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vSoC8xx.App\Entity\Telefono' shared service.
     *
     * @return \App\Entity\Telefono
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vSoC8xx": it references class "App\\Entity\\Telefono" but no such service exists.');
    }
}
