<?php

namespace Container04fbywN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QBmovtKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QBmovtK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QBmovtK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'titulo' => ['privates', '.errored..service_locator.QBmovtK.App\\Entity\\Titulo', NULL, 'Cannot autowire service ".service_locator.QBmovtK": it references class "App\\Entity\\Titulo" but no such service exists.'],
            'tituloRepository' => ['privates', 'App\\Repository\\TituloRepository', 'getTituloRepositoryService', true],
        ], [
            'titulo' => 'App\\Entity\\Titulo',
            'tituloRepository' => 'App\\Repository\\TituloRepository',
        ]);
    }
}
