<?php

namespace Container04fbywN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D4a3JnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d_4a3Jn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d_4a3Jn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'examenFinalRepository' => ['privates', 'App\\Repository\\ExamenFinalRepository', 'getExamenFinalRepositoryService', true],
        ], [
            'examenFinalRepository' => 'App\\Repository\\ExamenFinalRepository',
        ]);
    }
}
