<?php

namespace Container04fbywN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamenFinal2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VwQjRCK.App\Entity\ExamenFinal' shared service.
     *
     * @return \App\Entity\ExamenFinal
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VwQjRCK": it references class "App\\Entity\\ExamenFinal" but no such service exists.');
    }
}
