<?php

namespace Container04fbywN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamenAlumnoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rUzdFWK.App\Entity\ExamenAlumno' shared service.
     *
     * @return \App\Entity\ExamenAlumno
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.rUzdFWK": it references class "App\\Entity\\ExamenAlumno" but no such service exists.');
    }
}
