<?php

namespace Container04fbywN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalidadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QrC_.Ng.App\Entity\Localidad' shared service.
     *
     * @return \App\Entity\Localidad
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QrC_.Ng": it references class "App\\Entity\\Localidad" but no such service exists.');
    }
}
