<?php

namespace Container04fbywN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTurno2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GlfVhgC.App\Entity\Turno' shared service.
     *
     * @return \App\Entity\Turno
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.GlfVhgC": it references class "App\\Entity\\Turno" but no such service exists.');
    }
}
