<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Asignatura extends \App\Entity\Asignatura implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'anio', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'programa', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'tecnicatura', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'examenFinals', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'correlativa', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'cursada'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'anio', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'programa', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'tecnicatura', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'examenFinals', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'correlativa', '' . "\0" . 'App\\Entity\\Asignatura' . "\0" . 'cursada'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Asignatura $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnio(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnio', []);

        return parent::getAnio();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnio(int $anio): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnio', [$anio]);

        return parent::setAnio($anio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrograma(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrograma', []);

        return parent::getPrograma();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrograma(string $programa): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrograma', [$programa]);

        return parent::setPrograma($programa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTecnicatura(): ?\App\Entity\Tecnicatura
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTecnicatura', []);

        return parent::getTecnicatura();
    }

    /**
     * {@inheritDoc}
     */
    public function setTecnicatura(?\App\Entity\Tecnicatura $tecnicatura): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTecnicatura', [$tecnicatura]);

        return parent::setTecnicatura($tecnicatura);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getExamenFinals(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamenFinals', []);

        return parent::getExamenFinals();
    }

    /**
     * {@inheritDoc}
     */
    public function addExamenFinal(\App\Entity\ExamenFinal $examenFinal): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExamenFinal', [$examenFinal]);

        return parent::addExamenFinal($examenFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExamenFinal(\App\Entity\ExamenFinal $examenFinal): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExamenFinal', [$examenFinal]);

        return parent::removeExamenFinal($examenFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrelativa(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrelativa', []);

        return parent::getCorrelativa();
    }

    /**
     * {@inheritDoc}
     */
    public function addCorrelativa(\App\Entity\Correlativa $correlativa): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCorrelativa', [$correlativa]);

        return parent::addCorrelativa($correlativa);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCorrelativa(\App\Entity\Correlativa $correlativa): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCorrelativa', [$correlativa]);

        return parent::removeCorrelativa($correlativa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCursada(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCursada', []);

        return parent::getCursada();
    }

    /**
     * {@inheritDoc}
     */
    public function addCursada(\App\Entity\Cursada $cursada): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCursada', [$cursada]);

        return parent::addCursada($cursada);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCursada(\App\Entity\Cursada $cursada): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCursada', [$cursada]);

        return parent::removeCursada($cursada);
    }

}
