<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Persona extends \App\Entity\Persona implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'apellido', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'fecha_nacimiento', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'dni_pasaporte', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'genero', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'partido', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'calle', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'piso', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'departamento', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'pasillo', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'pais', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'localidad', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'nombre'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'apellido', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'fecha_nacimiento', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'dni_pasaporte', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'genero', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'partido', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'calle', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'piso', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'departamento', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'pasillo', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'pais', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'localidad', '' . "\0" . 'App\\Entity\\Persona' . "\0" . 'nombre'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Persona $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', []);

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido(string $apellido): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', [$apellido]);

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', []);

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento(\DateTimeInterface $fecha_nacimiento): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', [$fecha_nacimiento]);

        return parent::setFechaNacimiento($fecha_nacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDniPasaporte(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDniPasaporte', []);

        return parent::getDniPasaporte();
    }

    /**
     * {@inheritDoc}
     */
    public function setDniPasaporte(string $dni_pasaporte): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDniPasaporte', [$dni_pasaporte]);

        return parent::setDniPasaporte($dni_pasaporte);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenero(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenero', []);

        return parent::getGenero();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenero(string $genero): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenero', [$genero]);

        return parent::setGenero($genero);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono(?string $telefono): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartido(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartido', []);

        return parent::getPartido();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartido(string $partido): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartido', [$partido]);

        return parent::setPartido($partido);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalle', []);

        return parent::getCalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalle(string $calle): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalle', [$calle]);

        return parent::setCalle($calle);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero(?string $numero): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getPiso(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPiso', []);

        return parent::getPiso();
    }

    /**
     * {@inheritDoc}
     */
    public function setPiso(?int $piso): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPiso', [$piso]);

        return parent::setPiso($piso);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartamento(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartamento', []);

        return parent::getDepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartamento(?string $departamento): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartamento', [$departamento]);

        return parent::setDepartamento($departamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasillo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasillo', []);

        return parent::getPasillo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasillo(?string $pasillo): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasillo', [$pasillo]);

        return parent::setPasillo($pasillo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais(): ?\App\Entity\Pais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', []);

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais(?\App\Entity\Pais $pais): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', [$pais]);

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad(): ?\App\Entity\Localidad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad(?\App\Entity\Localidad $localidad): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

}
