<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tecnicatura extends \App\Entity\Tecnicatura implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'duracion', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'cantidad_asignaturas', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'numero_resolucion', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'modalidad', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'asignatura', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'comision'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'duracion', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'cantidad_asignaturas', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'numero_resolucion', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'modalidad', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'asignatura', '' . "\0" . 'App\\Entity\\Tecnicatura' . "\0" . 'comision'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tecnicatura $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuracion(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuracion', []);

        return parent::getDuracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuracion(int $duracion): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuracion', [$duracion]);

        return parent::setDuracion($duracion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadAsignaturas(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadAsignaturas', []);

        return parent::getCantidadAsignaturas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadAsignaturas(?int $cantidad_asignaturas): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadAsignaturas', [$cantidad_asignaturas]);

        return parent::setCantidadAsignaturas($cantidad_asignaturas);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroResolucion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroResolucion', []);

        return parent::getNumeroResolucion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroResolucion(string $numero_resolucion): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroResolucion', [$numero_resolucion]);

        return parent::setNumeroResolucion($numero_resolucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getModalidad(): ?\App\Entity\Modalidad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModalidad', []);

        return parent::getModalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setModalidad(?\App\Entity\Modalidad $modalidad): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModalidad', [$modalidad]);

        return parent::setModalidad($modalidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsignatura(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsignatura', []);

        return parent::getAsignatura();
    }

    /**
     * {@inheritDoc}
     */
    public function addAsignatura(\App\Entity\Asignatura $asignatura): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAsignatura', [$asignatura]);

        return parent::addAsignatura($asignatura);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAsignatura(\App\Entity\Asignatura $asignatura): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAsignatura', [$asignatura]);

        return parent::removeAsignatura($asignatura);
    }

    /**
     * {@inheritDoc}
     */
    public function getComision(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComision', []);

        return parent::getComision();
    }

    /**
     * {@inheritDoc}
     */
    public function addComision(\App\Entity\Comision $comision): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComision', [$comision]);

        return parent::addComision($comision);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComision(\App\Entity\Comision $comision): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComision', [$comision]);

        return parent::removeComision($comision);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
