<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ExamenFinal extends \App\Entity\ExamenFinal implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'asignatura', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'presidente', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'vocal1', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'vocal2', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'examenAlumnos'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'asignatura', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'presidente', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'vocal1', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'vocal2', '' . "\0" . 'App\\Entity\\ExamenFinal' . "\0" . 'examenAlumnos'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ExamenFinal $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(?\DateTimeInterface $fecha): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsignatura(): ?\App\Entity\Asignatura
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsignatura', []);

        return parent::getAsignatura();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsignatura(?\App\Entity\Asignatura $asignatura): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsignatura', [$asignatura]);

        return parent::setAsignatura($asignatura);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresidente(): ?\App\Entity\Docente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresidente', []);

        return parent::getPresidente();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresidente(?\App\Entity\Docente $presidente): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresidente', [$presidente]);

        return parent::setPresidente($presidente);
    }

    /**
     * {@inheritDoc}
     */
    public function getVocal1(): ?\App\Entity\Docente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVocal1', []);

        return parent::getVocal1();
    }

    /**
     * {@inheritDoc}
     */
    public function setVocal1(?\App\Entity\Docente $vocal1): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVocal1', [$vocal1]);

        return parent::setVocal1($vocal1);
    }

    /**
     * {@inheritDoc}
     */
    public function getVocal2(): ?\App\Entity\Docente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVocal2', []);

        return parent::getVocal2();
    }

    /**
     * {@inheritDoc}
     */
    public function setVocal2(?\App\Entity\Docente $vocal2): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVocal2', [$vocal2]);

        return parent::setVocal2($vocal2);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getExamenAlumnos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamenAlumnos', []);

        return parent::getExamenAlumnos();
    }

    /**
     * {@inheritDoc}
     */
    public function addExamenAlumno(\App\Entity\ExamenAlumno $examenAlumno): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExamenAlumno', [$examenAlumno]);

        return parent::addExamenAlumno($examenAlumno);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExamenAlumno(\App\Entity\ExamenAlumno $examenAlumno): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExamenAlumno', [$examenAlumno]);

        return parent::removeExamenAlumno($examenAlumno);
    }

}
