<?php

namespace Container9zYj1Zb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DqTasREService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DqTasRE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DqTasRE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'provincium' => ['privates', '.errored..service_locator.DqTasRE.App\\Entity\\Provincia', NULL, 'Cannot autowire service ".service_locator.DqTasRE": it references class "App\\Entity\\Provincia" but no such service exists.'],
        ], [
            'provincium' => 'App\\Entity\\Provincia',
        ]);
    }
}
