<?php

namespace Container9zYj1Zb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X7dCCmRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X7dCCmR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X7dCCmR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'provinciaRepository' => ['privates', 'App\\Repository\\ProvinciaRepository', 'getProvinciaRepositoryService', true],
        ], [
            'provinciaRepository' => 'App\\Repository\\ProvinciaRepository',
        ]);
    }
}
