<?php

namespace Container9zYj1Zb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VSoC8xxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vSoC8xx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vSoC8xx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'telefono' => ['privates', '.errored..service_locator.vSoC8xx.App\\Entity\\Telefono', NULL, 'Cannot autowire service ".service_locator.vSoC8xx": it references class "App\\Entity\\Telefono" but no such service exists.'],
            'telefonoRepository' => ['privates', 'App\\Repository\\TelefonoRepository', 'getTelefonoRepositoryService', true],
        ], [
            'telefono' => 'App\\Entity\\Telefono',
            'telefonoRepository' => 'App\\Repository\\TelefonoRepository',
        ]);
    }
}
