<?php

namespace Container9zYj1Zb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCursada2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xZJ6eXh.App\Entity\Cursada' shared service.
     *
     * @return \App\Entity\Cursada
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.xZJ6eXh": it references class "App\\Entity\\Cursada" but no such service exists.');
    }
}
