<?php

namespace Container9zYj1Zb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPais2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HuJItRo.App\Entity\Pais' shared service.
     *
     * @return \App\Entity\Pais
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HuJItRo": it references class "App\\Entity\\Pais" but no such service exists.');
    }
}
