<?php

namespace Container9zYj1Zb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevistaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5fwZ1jo.App\Entity\Revista' shared service.
     *
     * @return \App\Entity\Revista
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.5fwZ1jo": it references class "App\\Entity\\Revista" but no such service exists.');
    }
}
